-- MySQL Script generated by MySQL Workbench
-- Thu May 29 09:27:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_certifica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_certifica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_certifica` ;
USE `db_certifica` ;

-- -----------------------------------------------------
-- Table `db_certifica`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_certifica`.`Curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeCurso` VARCHAR(45) NOT NULL,
  `cargaHorariaAtivComplement` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_certifica`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_certifica`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `anoNascimento` DATE NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `endereco` VARCHAR(45) NULL,
  `codigoMatricula` INT NULL,
  `funcao` ENUM('ADMINSITRADOR', 'COORDENADOR', 'ALUNO') NOT NULL,
  `horasValidadas` INT NOT NULL,
  `status` ENUM("ATIVO", "INATIVO", "PENDENTE") NOT NULL,
  `Curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_Curso_idx` (`Curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Curso`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `db_certifica`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_certifica`.`TipoAtividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_certifica`.`TipoAtividade` (
  `id` INT NOT NULL,
  `nomeAtividade` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_certifica`.`CursoAtividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_certifica`.`CursoAtividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargaHorariaMaxima` INT NOT NULL,
  `equivalencia` VARCHAR(45) NOT NULL,
  `TipoAtividade_id` INT NOT NULL,
  `Curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CursoAtividade_TipoAtividade1_idx` (`TipoAtividade_id` ASC) VISIBLE,
  INDEX `fk_CursoAtividade_Curso1_idx` (`Curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_CursoAtividade_TipoAtividade1`
    FOREIGN KEY (`TipoAtividade_id`)
    REFERENCES `db_certifica`.`TipoAtividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CursoAtividade_Curso1`
    FOREIGN KEY (`Curso_id`)
    REFERENCES `db_certifica`.`Curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_certifica`.`Comprovante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_certifica`.`Comprovante` (
  `id` INT NOT NULL,
  `horas` INT NOT NULL,
  `status` ENUM('PENDENTE', 'APROVADO', 'RECUSADO') NOT NULL,
  `comentario` VARCHAR(45) NULL,
  `arquivo` VARCHAR(45) NOT NULL,
  `Usuario_id` INT NOT NULL,
  `Usuario_Curso_id` INT NOT NULL,
  `CursoAtividade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comprovante_Usuario1_idx` (`Usuario_id` ASC, `Usuario_Curso_id` ASC) VISIBLE,
  INDEX `fk_Comprovante_CursoAtividade1_idx` (`CursoAtividade_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comprovante_Usuario1`
    FOREIGN KEY (`Usuario_id` , `Usuario_Curso_id`)
    REFERENCES `db_certifica`.`Usuario` (`id` , `Curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comprovante_CursoAtividade1`
    FOREIGN KEY (`CursoAtividade_id`)
    REFERENCES `db_certifica`.`CursoAtividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
